# Page settings

baseURL = "https://cric96.github.io/resume/"
languageCode = "en"
title = "GA Resume"
theme = ["hugo-resume", "hugo-cite"]

[params]
    author = "Gianluca Aguzzi"
    description = "Research resume"


    primaryColor = "#f57c00"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Gianluca Aguzzi"
        tagline = "Postdoctoral Researcher"
        avatar = "me.jpeg"

    [params.contact]
        enable = true
        location = "Cesena"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "gianluca.aguzzi@unibo.it"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://www.unibo.it/sitoweb/gianluca.aguzzi/en"
        text = "https://www.unibo.it/sitoweb/gianluca.aguzzi/en"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Scala/Java/Kotlin"
        [[params.skills.list.items]]
        details = "C/C++/C#"
        [[params.skills.list.items]]
        details = "Python/Sklearn/Tensorflow"
        [[params.skills.list.items]]
        details = "Logic programming"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Functional (and Reactive) programming"
        [[params.skills.list.items]]
        details = "Actor-based desing"


    [params.education]
        enable = true
        [[params.education.list]]
        degree = "PhD in Computer Science and Software Engineering"
        university = "Alma Mater Studiorum"
        dates = "2020 - 2023"
        vote = "with distiction"
        [[params.education.list]]
        degree = "MSc in Computer Science and Software Engineering"
        university = "Alma Mater Studiorum"
        dates = "2018 - 2020"
        vote = "110 cum laude"
        [[params.education.list]]
        degree = "BSc in Computer Science and Software Engineering"
        university = "Alma Mater Studiorum"
        dates = "2015 - 2018"
        vote = "110 cum laude"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Italian"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Running"
        [[params.interests.list]]
        name = "Gaming"
        [[params.interests.list]]
        name = "Technology"
        [[params.interests.list]]
        name = "Travelling"

    [params.summary]
        enable = true
        text = "I am a Postdoctoral research in Computer Science at the Department of Computer Science and Engineering of the University of Bologna (Italy). My research ranges from multi-agent learning, aggregate computing, distributed algorithms and engineering methodologies, with the goal of finding a systematic procedure to synthesise and deploy self-organising behaviours of predictable outcomes for CPSW. For more details, please look at bibliography."
    [params.experience]
        enable = true
        [[params.experience.list]]
        title = "Adjunt Professor @ Software Design and Development (PSS)"
        dates = "2023-2024"
        company = "Università di Bologna -- ALMA MATER STUDIORUM"
        details = "Details @ https://www.unibo.it/en/study/phd-professional-masters-specialisation-schools-and-other-programmes/course-unit-catalogue/course-unit/2024/498808"

        [[params.experience.list]]
        title = "Tutor @ Paradigmi di Progettazione e Sviluppo (PPS)"
        dates = "2022-2024"
        company = "Università di Bologna -- ALMA MATER STUDIORUM"
        details = "Details @ https://www.unibo.it/it/didattica/insegnamenti/insegnamento/2022/412597"
        
        [[params.experience.list]]
        title = "Tutor @ Concurrent & Distributed Programming (PCD)"
        dates = "2022-2024"
        company = "Università di Bologna -- ALMA MATER STUDIORUM"
        details = "Details @ https://www.unibo.it/it/didattica/insegnamenti/insegnamento/2021/412598"

        [[params.experience.list]]
        title = "Tutor in coding training courses for teachers"
        dates = "2019 - 2019"
        company = "Criad Coding"
        details = "In this experience, I paired a professional teacher in classes composed of people with a different background and of a different age. I was also responsible for the development of the course material and the management of the course itself. This experience has allowed me to develop my communication skills and my ability to adapt to different situations."
    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "ScaFi Web"
        meta = "Open Source"
        tagline = "ScaFi Web (https://github.com/scafi/scafi-web) is an online playground used to facilitate aggregate programming (i.e. a novel way to program collective adaptive systems, my area of interest). It was my master thesis work and then it was refined for research reason. Currently, the system is hosted on https://scafi.github.io/web/"
        
        [[params.projects.list]]
        title = "ScaFi"
        meta = "Co-Mantainer"
        tagline = "ScaFi (https://github.com/scafi/) is a toolkit for developing Aggregate Computing applications."
        
    [params.international]
        enable = true
        
        [[params.international.list]]
        title = "Student Volunteer @ ACSOS, ICDCS"
        dates = "2022"
        [[params.international.list]]
        title = "Artefact Evaluation Committe @ COORDINATION, ACSOS, PerCOM"
        dates = "2022-2024"
       
    [params.pubblications]
        enable = true

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/cric96"
        title = "cric96"
        
        [[params.social.list]]
        icon = "fab fa-stack-overflow"
        url = "https://stackoverflow.com/users/10295847/gianluca-aguzzi"
        title = "gianluca-aguzzi"
            
        [[params.social.list]]
        icon = "fab fa-gitlab"
        url = "https://gitlab.com/gianluca.aguzzi"
        title = "gianluca.aguzzi"
